[package]
name = "web_server"
authors = ["Arthur Damasceno <damascenoarthur653@gmail.com>"]
version = "0.1.0"
license = "MIT"
edition = "2021"

[dependencies]
thread_pool = { path = "./thread_pool" }
