[package]
name = "web_server"
authors = ["Arthur Damasceno <damascenoarthur653@gmail.com>"]
version = "0.1.0"
license = "MIT"
edition = "2021"

[dependencies]
async-std = { version = "1.10.0", features = ["attributes"] }
